---
baseURL: https://magrathea.guide/
languageCode: en-US
pluralizeListTitles: false
publishDir: docs
sectionPagesMenu: main
taxonomies:
    crew: crew
    commission: commissions
    project: projects
theme: trillian
title: Magrathea
